# Generated by Django 3.1.13 on 2021-07-28 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('califish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='pictuer',
            new_name='picture',
        ),
    ]
