# Generated by Django 3.1.13 on 2021-07-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('califish', '0004_auto_20210728_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
